version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: mysql_image
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accwe_hospital
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile.maven
    image: accwe_hospital
    ports:
      - "3000:8080"
    depends_on:
      - db